name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v6
      - run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_WARNINGS: deny
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v6
      - run: cargo check --workspace --all-targets --keep-going

  clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_WARNINGS: deny
    steps:
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v6
      - run: cargo clippy --workspace --all-targets --keep-going

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v6
      - run: cargo test --workspace
